# Generated by Django 2.2.9 on 2020-04-29 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20200429_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpackage',
            name='did',
            field=models.CharField(default='000-000', max_length=7, validators=[django.core.validators.RegexValidator(message='ID doesnt comply', regex='^\\d{3}\\-\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='pid',
            field=models.CharField(default='000-000-000', max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='ID doesnt comply', regex='^\\d{3}\\-\\d{3}-\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='sid',
            field=models.CharField(default='000', max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='ID doesnt comply', regex='^\\d{3}$')]),
        ),
    ]
