# Generated by Django 2.2.9 on 2020-05-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20200429_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpackage',
            name='starttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
