# Generated by Django 2.2.9 on 2020-01-11 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurveyFormSubmission',
        ),
    ]
