# Generated by Django 2.1.7 on 2019-07-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190703_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
