# Generated by Django 2.2.3 on 2019-07-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190703_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='e2808be0-8a40-454b-bb58-4ffce2f31be3', max_length=36, null=True),
        ),
    ]
