# Generated by Django 2.2.3 on 2019-07-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190705_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
