# Generated by Django 2.2.7 on 2019-11-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190716_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education_data',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='platform_data',
            field=models.TextField(null=True),
        ),
    ]
