# Generated by Django 2.2.7 on 2019-11-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20191114_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sources',
            field=models.TextField(null=True),
        ),
    ]
