# Generated by Django 2.2.9 on 2020-05-25 23:23

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200525_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='sections',
            field=wagtail.core.fields.StreamField([('s_about', wagtail.core.blocks.StructBlock([('pages', wagtail.core.blocks.StreamBlock([('page', wagtail.core.blocks.StructBlock([('blink', wagtail.core.blocks.CharBlock(blank=True, classname='full')), ('use_image', wagtail.core.blocks.BooleanBlock(classname='full', default=False, help_text='Use picture instead of blink', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(classname='full', required=False)), ('boxes', wagtail.core.blocks.StreamBlock([('box', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(blank=True, classname='full title', icon='title', null=True)), ('content', wagtail.core.blocks.RichTextBlock(blank=True, classname='full', null=True))], blank=False, icon='doc-full', null=True))], blank=False, null=True))], blank=False, icon='cogs', null=True))], blank=False, null=True))], blank=False, icon='radio-empty', null=True)), ('s_amodt', wagtail.core.blocks.StructBlock([('modt', wagtail.core.blocks.CharBlock(classname='full', default="Sky's The Limit", max_length=16))], blank=False, icon='pilcrow', null=True))], null=True),
        ),
    ]
