# Generated by Django 2.2.9 on 2020-01-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepage',
            name='platform_data',
            field=models.TextField(null=True),
        ),
    ]
