# Generated by Django 2.2.9 on 2020-01-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profilepage_platform_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepage',
            name='sources',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profilepage',
            name='platform_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
