# Generated by Django 2.2.9 on 2020-01-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20200117_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepage',
            name='newsletter',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
