# Generated by Django 2.2.9 on 2020-01-30 18:22

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_profilepage_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepage',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='profilepage',
            name='organizations',
        ),
        migrations.RemoveField(
            model_name='profilepage',
            name='platforms',
        ),
        migrations.AlterField(
            model_name='profilepage',
            name='main',
            field=wagtail.core.fields.StreamField([('top_language', wagtail.core.blocks.StructBlock([('theme', wagtail.core.blocks.CharBlock(blank=True, help_text='Bold header text', max_length=64, null=True))], blank=True, icon='fa-instagram', null=True)), ('calendar', wagtail.core.blocks.StructBlock([('theme', wagtail.core.blocks.CharBlock(blank=True, help_text='Bold header text', max_length=64, null=True))], blank=True, icon='home', null=True))], blank=True, null=True),
        ),
    ]
