# Generated by Django 2.2.9 on 2020-01-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_auto_20200130_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepage',
            name='bids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilepage',
            name='tids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
