# Generated by Django 2.1.7 on 2019-07-03 11:41

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('user.user',),
        ),
    ]
