# Generated by Django 2.1.7 on 2019-07-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('first_name',)},
        ),
    ]
