# Generated by Django 2.2.9 on 2020-05-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_token', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('session_name', models.CharField(blank=True, max_length=16, null=True)),
                ('session_scope', models.CharField(blank=True, max_length=256, null=True)),
                ('session_from', models.DateField(blank=True, null=True)),
                ('session_to', models.DateField(blank=True, null=True)),
                ('session_room', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
    ]
