# Generated by Django 2.2.9 on 2020-01-11 22:04

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationformpage',
            name='supported_gitlabs',
            field=wagtail.core.fields.StreamField([('gitlab_server', wagtail.core.blocks.StructBlock([('organisation', wagtail.core.blocks.CharBlock(blank=False, classname='full title', help_text='The owner of gitlab server.', null=True)), ('domain', wagtail.core.blocks.CharBlock(blank=False, classname='full title', help_text='The domain of supported gitlab server.', null=True))], blank=False, icon='home', null=True))], null=True),
        ),
    ]
