# Generated by Django 2.2.9 on 2020-05-29 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_assoc_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='assoc_sessions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='session.Session', verbose_name='Associated Session'),
        ),
    ]
